# site settings
title: cvless
description: Jekyll theme for a beautiful online CV
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme
url: https://cvless.netlify.app
baseurl: ""
permalink: pretty
repo: https://github.com/username/username.github.io

# author settings
author:
  name: Place Holder
  email: username@domain.com
photo: /assets/jpg/photo.jpg

# social media links
social:
  facebook: username
  github: username
  instagram: username
  linkedin: username
  stackoverflow: 0000000/username
  twitter: username

# build settings
exclude:
  - LICENSE
  - README.md
