title: cvless
description: Jekyll theme for a beautiful online CV
baseurl: ""
url: https://piazzai.github.io/cvless

theme: cvless

# site settings
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme
permalink: pretty
repo: https://github.com/username/username.github.io

# author settings
author:
  name: Place Holder
  email: username@domain.com
photo: assets/files/photo.jpg

# social media links
social:
  facebook: username
  github: username
  instagram: username
  linkedin: username
  stackoverflow: 0000000/username
  x: username

# build settings
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
